<?php get_header(); ?>
<main>
<section class="rsi-editorial-hero" id="accueil">
  <div class="cvng-wrap rsi-editorial-grid">
    <div class="rsi-editorial-copy">
      <div class="cvng-kicker">SYSTÈMES D’INFORMATION · TRANSFORMATION · PERFORMANCE</div>
      <h1>Regards <b>SI</b></h1>
      <p class="rsi-manifesto">La technique n’est jamais le sujet.<br><strong>Ce que l’entreprise en fait, si.</strong></p>
      <p class="rsi-intro">Une revue éditoriale sur les systèmes d’information, la finance, la data et l’IA — regardés depuis l’entreprise, ses décisions et ses usages.</p>
      <div class="rsi-hero-links"><a href="#a-laffiche">Lire à l’affiche →</a><a href="#observatoire">Explorer l’Observatoire SI</a></div>
    </div>
    <aside class="rsi-editorial-aside">
      <div class="rsi-aside-label">LA LIGNE ÉDITORIALE</div>
      <p>Comprendre les transformations.<br>Interroger les évidences.<br>Mesurer ce qui compte.<br>Partager l’expérience.</p>
      <div class="rsi-doctrine"><span>BUSINESS FIRST</span><span>RISK BASED</span><span>IT AS AN ENABLER</span></div>
    </aside>
  </div>
</section>
<section class="rsi-topics"><div class="cvng-wrap rsi-topics-grid"><div><span>01</span><strong>Systèmes d’information</strong><small>Gouvernance · ERP · transformation</small></div><div><span>02</span><strong>Finance & DAF</strong><small>Processus · pilotage · performance</small></div><div><span>03</span><strong>Data & IA</strong><small>Usages · décision · valeur</small></div></div></section>
<section class="cvng-section" id="a-laffiche"><div class="cvng-wrap"><div class="cvng-section-head"><div><div class="cvng-eyebrow">À l’affiche</div><h2 class="cvng-section-title">Une conviction à mettre en débat.</h2></div><span class="cvng-section-index">ÉDITORIAL</span></div><article class="rsi-lead-story"><div class="rsi-story-index">01</div><div><div class="cvng-tag">Gouvernance · Doctrine</div><h3>La DSI n’a pas à être alignée avec le Business. Elle doit être au service du Business.</h3><p>La performance du SI est subordonnée à celle de l’entreprise. Une distinction qui change la manière de gouverner, d’arbitrer et de transformer.</p><a class="cvng-text-link" href="#analyses">Lire l’analyse →</a></div></article></div></section>
<section class="cvng-section cvng-section-pale" id="analyses"><div class="cvng-wrap"><div class="cvng-section-head"><div><div class="cvng-eyebrow">Entre les lignes</div><h2 class="cvng-section-title">Analyses, convictions, dossiers.</h2></div><span class="cvng-section-index">DÉCRYPTER</span></div><div class="cvng-grid3"><article class="cvng-card"><div class="cvng-card-kicker">Systèmes d’information</div><h3>Le SI est un outil. Pas une finalité.</h3><p>Replacer la technologie dans la chaîne de valeur de l’entreprise.</p></article><article class="cvng-card"><div class="cvng-card-kicker">Risque & performance</div><h3>Le risque zéro est une mauvaise cible.</h3><p>Optimiser le risque global plutôt que protéger localement la DSI.</p></article><article class="cvng-card"><div class="cvng-card-kicker">Data & IA</div><h3>La valeur vient des usages.</h3><p>Une technologie ne crée de valeur que lorsqu’elle améliore une décision ou une action.</p></article></div></div></section>
<section class="cvng-section cvng-observatory" id="observatoire"><div class="cvng-wrap cvng-observatory-grid"><div><div class="cvng-eyebrow cvng-eyebrow-light">L’Observatoire SI</div><h2 class="cvng-section-title cvng-title-light">Des données pour sortir des impressions.</h2><p class="cvng-observatory-intro">Indicateurs, séries historiques, benchmarks et analyses pour confronter les convictions aux faits.</p></div><div class="cvng-metrics"><div><strong>01</strong><span>Performance SI</span></div><div><strong>02</strong><span>Risque & résilience</span></div><div><strong>03</strong><span>Transformation & ERP</span></div><div><strong>04</strong><span>Data & IA</span></div></div></div></section>
<section class="cvng-section" id="en-pratique"><div class="cvng-wrap"><div class="cvng-section-head"><div><div class="cvng-eyebrow">En pratique</div><h2 class="cvng-section-title">Quand les principes rencontrent le terrain.</h2></div><span class="cvng-section-index">EXPÉRIENCE</span></div><div class="rsi-practice-grid"><article><strong>ERP & transformation</strong><p>Ce que les projets révèlent de l’organisation — au-delà de l’outil.</p></article><article><strong>SI Finance</strong><p>Processus, contrôle, données et décisions dans un même système.</p></article><article><strong>Data & IA</strong><p>Partir des usages avant de partir de la technologie.</p></article></div></div></section>
<section class="cvng-section cvng-rudy" id="rudy"><div class="cvng-wrap rsi-author-grid"><div><div class="cvng-eyebrow">L’auteur</div><h2 class="cvng-section-title">Rudy Desnos</h2><p class="rsi-author-intro">Plus de vingt-cinq ans de systèmes d’information, de la technique au pilotage, au croisement de la finance, des ERP, de la data et de la transformation d’entreprise.</p><a class="cvng-text-link" href="https://www.linkedin.com/in/rudy-desnos/">Voir le parcours →</a></div><blockquote>« Une DSI ne se juge pas à la sophistication de son SI, mais à ce que ce SI permet à l’entreprise d’accomplir. »</blockquote></div></section>
<section class="rsi-closing"><div class="cvng-wrap"><span>REGARDS SI</span><p>Comprendre. Partager. Éclairer.</p></div></section>
</main>
<?php get_footer(); ?>
